logging:
  level:
    com.example.projectboard: DEBUG
    org.springframework.core.env.PropertySourcesPropertyResolver: TRACE

spring:

#  profiles:
#    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: ${db_url}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql

token:
  secret: ${token_secret}

springdoc:

  swagger-ui:
    enabled: true
    path: ${swagger_uri}

server:
  port: 9090